/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import com.codename1.io.rest.Response;
import com.codename1.io.rest.Rest;
import com.codename1.location.Location;
import com.codename1.location.LocationManager;
import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import static com.codename1.ui.events.ActionEvent.Type.Response;
import com.codename1.ui.util.Resources;
import java.util.Map;

/**
 *
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
        Location position = LocationManager.getLocationManager().getCurrentLocationSync();
    }


    @Override
    protected void onLogin_LoginAction(Component c, ActionEvent event) {
        
    }

    @Override
    protected void onMain_RefreshAction(Component c, ActionEvent event) {
        Location position = LocationManager.getLocationManager().getCurrentLocationSync();
        String lat = Double.toString(position.getLatitude());
        String lon = Double.toString(position.getLongitude());
        String myUrl = "http://api.openweathermap.org/data/2.5/weather?lat="+lat+"&lon="+lon+"&appid=891ce0a8cb808764ee9ab6a0bbb52187";
        Response<Map> jsonData = Rest.get(myUrl).getAsJsonMap();

        Map tempData = (Map) jsonData.getResponseData().get("main");
        double temperature = (double)tempData.get("temp");
        double cTemp = temperature -273.15;
        int l = (int) cTemp;
        findTemp().setText(Integer.toString(l) + "C");
        
        String cityData = (String) jsonData.getResponseData().get("name");
        findOrt().setText(cityData);
        
        Map wetterData = (Map) jsonData.getResponseData().get("weather");
        String wetter = (String) wetterData.get("main");
        findWetter().setText(wetter);
        
    }
}
