/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import bbbaden.LB.java.Information;
import com.codename1.io.rest.Response;
import com.codename1.io.rest.Rest;
import com.codename1.location.Location;
import com.codename1.location.LocationManager;
import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import static com.codename1.ui.events.ActionEvent.Type.Response;
import com.codename1.ui.util.Resources;
import java.util.Map;

/**
 *
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
        
    }


    @Override
    protected void onLogin_LoginAction(Component c, ActionEvent event) {
        
    }

    @Override
    protected void onMain_RefreshAction(Component c, ActionEvent event) {
        Information info = new Information();
        info.refresh();
        
        findTemp().setText(info.getTemp() + "C");
        
        findOrt().setText(info.getCityData());
        
        findWetter().setText(info.getWetter());
        
    }

    @Override
    protected void onWetterOrt_AusgebenAction(Component c, ActionEvent event) {
        Information info = new Information();
        
        info.setCity(findTextArea().getText());
        info.cityWetter();
        findTempLbl().setText(info.getTemp() + "C");
        findWetterLbl().setText(info.getWetter());
        
        
    }

    @Override
    protected void onMain_Seite2Action(Component c, ActionEvent event) {
        showForm("WetterOrt", null);
    }

    
}
